# Generated by Django 5.2.15 on 2026-06-03 04:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'bâtiment',
                'verbose_name_plural': 'bâtiments',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=150)),
                ('actif', models.BooleanField(default=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='logistics.batiment')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['batiment__code', 'code'],
                'unique_together': {('batiment', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, verbose_name='N° chambre')),
                ('actif', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chambres', to='logistics.service')),
            ],
            options={
                'verbose_name': 'chambre',
                'verbose_name_plural': 'chambres',
                'ordering': ['service__code', 'numero'],
                'unique_together': {('service', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=10, verbose_name='N° lit')),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('occupe', 'Occupé'), ('maintenance', 'Maintenance')], default='libre', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lits', to='logistics.chambre')),
            ],
            options={
                'verbose_name': 'lit',
                'verbose_name_plural': 'lits',
                'ordering': ['chambre__numero', 'numero'],
                'indexes': [models.Index(fields=['statut'], name='logistics_l_statut_dee9b2_idx')],
                'unique_together': {('chambre', 'numero')},
            },
        ),
    ]
