# Generated by Django 5.2.15 on 2026-06-03 05:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentStock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('forme', models.CharField(blank=True, max_length=80)),
                ('quantite_stock', models.PositiveIntegerField(default=0)),
                ('unite', models.CharField(default='unité', max_length=30)),
                ('seuil_alerte', models.PositiveIntegerField(default=10)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'médicament en stock',
                'verbose_name_plural': 'stock pharmacie',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='OrdreDispensation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('prepare', 'Préparé'), ('dispense', 'Dispensé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('prepare_le', models.DateTimeField(blank=True, null=True)),
                ('dispense_le', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('pharmacien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensations_effectuees', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ordre_dispensation', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'ordre de dispensation',
                'verbose_name_plural': 'ordres de dispensation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneDispensation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('ligne_prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensations', to='prescriptions.ligneprescription')),
                ('medicament_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_dispensation', to='pharmacie.medicamentstock')),
                ('ordre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacie.ordredispensation')),
            ],
            options={
                'verbose_name': 'ligne de dispensation',
                'verbose_name_plural': 'lignes de dispensation',
            },
        ),
        migrations.AddIndex(
            model_name='ordredispensation',
            index=models.Index(fields=['statut'], name='pharmacie_o_statut_d8762b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lignedispensation',
            unique_together={('ordre', 'ligne_prescription')},
        ),
    ]
