# Generated by Django 5.2.15 on 2026-06-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentstock',
            name='date_peremption',
            field=models.DateField(blank=True, null=True, verbose_name='Date de péremption'),
        ),
    ]
