# Generated by Django 5.2.15 on 2026-06-03 04:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitalisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSoins',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='actif', max_length=20)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_soins_crees', to=settings.AUTH_USER_MODEL)),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans_soins', to='hospitalisation.hospitalisation')),
            ],
            options={
                'verbose_name': 'plan de soins',
                'verbose_name_plural': 'plans de soins',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ConstanteVitale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('tension_systolique', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tension_diastolique', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('frequence_cardiaque', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('frequence_respiratoire', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('saturation_o2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('glycemie', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mesure_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='constantes_vitales', to='hospitalisation.hospitalisation')),
                ('infirmier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constantes_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'constante vitale',
                'verbose_name_plural': 'constantes vitales',
                'ordering': ['-mesure_le'],
                'indexes': [models.Index(fields=['mesure_le'], name='soins_const_mesure__659315_idx')],
            },
        ),
        migrations.CreateModel(
            name='InterventionInfirmiere',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_intervention', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('realisee_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions_infirmieres', to='hospitalisation.hospitalisation')),
                ('infirmier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_realisees', to=settings.AUTH_USER_MODEL)),
                ('plan_soins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='soins.plansoins')),
            ],
            options={
                'verbose_name': 'intervention infirmière',
                'verbose_name_plural': 'interventions infirmières',
                'ordering': ['-realisee_le'],
                'indexes': [models.Index(fields=['realisee_le'], name='soins_inter_realise_47ceb6_idx')],
            },
        ),
        migrations.CreateModel(
            name='DosePlanifiee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicament', models.CharField(max_length=200)),
                ('posologie', models.CharField(max_length=100)),
                ('heure_prevue', models.DateTimeField()),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('administree', 'Administrée'), ('omise', 'Omise')], default='planifiee', max_length=20)),
                ('administree_le', models.DateTimeField(blank=True, null=True)),
                ('infirmier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doses_administrees', to=settings.AUTH_USER_MODEL)),
                ('plan_soins', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doses', to='soins.plansoins')),
            ],
            options={
                'verbose_name': 'dose planifiée',
                'verbose_name_plural': 'doses planifiées',
                'ordering': ['heure_prevue'],
                'indexes': [models.Index(fields=['heure_prevue'], name='soins_dosep_heure_p_a008e0_idx'), models.Index(fields=['statut'], name='soins_dosep_statut_bbcf70_idx')],
            },
        ),
    ]
