# Generated by Django 5.2.10 on 2026-07-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('organization_name', models.CharField(default='SGHL — Centre Hospitalier', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='support@sghl.local', max_length=254)),
                ('finess_number', models.CharField(blank=True, default='', max_length=20, verbose_name='N° FINESS')),
                ('mfa_required', models.BooleanField(default=True)),
                ('session_timeout_minutes', models.PositiveSmallIntegerField(default=15)),
                ('max_login_attempts', models.PositiveSmallIntegerField(default=5)),
                ('audit_logging_enabled', models.BooleanField(default=True)),
                ('encryption_level', models.CharField(default='standard', max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, default='')),
                ('hl7_enabled', models.BooleanField(default=False)),
                ('fhir_enabled', models.BooleanField(default=False)),
                ('insurance_api_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'configuration établissement',
                'verbose_name_plural': 'configuration établissement',
            },
        ),
    ]
