# Generated by Django 5.2.10 on 2026-07-11 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageInterne',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sujet', models.CharField(max_length=200)),
                ('corps', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('lu_le', models.DateTimeField(blank=True, null=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message interne',
                'verbose_name_plural': 'messages internes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destinataire', 'lu'], name='messagerie__destina_9f4f2e_idx'), models.Index(fields=['expediteur'], name='messagerie__expedit_f44805_idx')],
            },
        ),
    ]
