# Generated by Django 5.2.15 on 2026-06-03 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_heure', models.DateTimeField()),
                ('duree_minutes', models.PositiveSmallIntegerField(default=30)),
                ('motif', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé'), ('absent', 'Absent')], default='planifie', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('confirme_le', models.DateTimeField(blank=True, null=True)),
                ('annule_le', models.DateTimeField(blank=True, null=True)),
                ('motif_annulation', models.CharField(blank=True, max_length=255)),
                ('annule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_annules', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_crees', to=settings.AUTH_USER_MODEL)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendez_vous_medecin', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendez_vous', to='patients.patient')),
            ],
            options={
                'verbose_name': 'rendez-vous',
                'verbose_name_plural': 'rendez-vous',
                'ordering': ['date_heure'],
                'indexes': [models.Index(fields=['date_heure'], name='rendezvous__date_he_08ff5b_idx'), models.Index(fields=['statut'], name='rendezvous__statut_80dbef_idx'), models.Index(fields=['medecin', 'date_heure'], name='rendezvous__medecin_f724aa_idx')],
            },
        ),
    ]
