# Generated by Django 5.2.10 on 2026-07-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0002_rappel_j1_envoye_le'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='lien_visio',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='type_consultation',
            field=models.CharField(choices=[('presentiel', 'Présentiel'), ('teleconsultation', 'Téléconsultation')], default='presentiel', max_length=20),
        ),
    ]
