# Generated by Django 5.2.15 on 2026-06-03 05:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitalisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code analyse')),
                ('libelle', models.CharField(max_length=255)),
                ('unite_reference', models.CharField(blank=True, max_length=50)),
                ('valeur_reference', models.CharField(blank=True, max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'analyse catalogue',
                'verbose_name_plural': 'catalogue analyses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CommandeAnalyse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('commandee', 'Commandée'), ('prelevee', 'Prélevée'), ('affectee', 'Affectée'), ('resultats_saisis', 'Résultats saisis'), ('validee', 'Validée'), ('publiee', 'Publiée'), ('annulee', 'Annulée')], default='commandee', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('preleve_le', models.DateTimeField(blank=True, null=True)),
                ('type_echantillon', models.CharField(blank=True, max_length=100)),
                ('reference_echantillon', models.CharField(blank=True, max_length=100)),
                ('affectee_le', models.DateTimeField(blank=True, null=True)),
                ('validee_le', models.DateTimeField(blank=True, null=True)),
                ('publiee_le', models.DateTimeField(blank=True, null=True)),
                ('affectee_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_affectees', to=settings.AUTH_USER_MODEL)),
                ('affectee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_realisees', to=settings.AUTH_USER_MODEL)),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_analyses', to='hospitalisation.hospitalisation')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_analyses_redigees', to=settings.AUTH_USER_MODEL)),
                ('preleve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prelevements_effectues', to=settings.AUTH_USER_MODEL)),
                ('publiee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_analyses_publiees', to=settings.AUTH_USER_MODEL)),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_analyses_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'commande analyse',
                'verbose_name_plural': 'commandes analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommandeAnalyse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_analyse', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=255)),
                ('unite_reference', models.CharField(blank=True, max_length=50)),
                ('valeur_reference', models.CharField(blank=True, max_length=100)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='laboratoire.commandeanalyse')),
            ],
            options={
                'verbose_name': 'ligne commande analyse',
                'verbose_name_plural': 'lignes commande analyse',
                'ordering': ['code_analyse'],
            },
        ),
        migrations.CreateModel(
            name='ResultatAnalyse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valeur', models.CharField(max_length=100)),
                ('unite', models.CharField(blank=True, max_length=50)),
                ('commentaire', models.TextField(blank=True)),
                ('ligne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='laboratoire.lignecommandeanalyse')),
                ('saisi_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats_analyses_saisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'résultat analyse',
                'verbose_name_plural': 'résultats analyses',
            },
        ),
        migrations.AddIndex(
            model_name='commandeanalyse',
            index=models.Index(fields=['statut'], name='laboratoire_statut_6c85af_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeanalyse',
            index=models.Index(fields=['created_at'], name='laboratoire_created_675fc0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lignecommandeanalyse',
            unique_together={('commande', 'code_analyse')},
        ),
    ]
