# Generated by Django 5.2.10 on 2026-07-10 00:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('type_certification', models.CharField(max_length=100)),
                ('duree_validite_mois', models.PositiveSmallIntegerField(blank=True, help_text='Durée de validité en mois (null = pas de renouvellement automatique).', null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'certification',
                'verbose_name_plural': 'certifications',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('formateur', models.CharField(max_length=150)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('capacite_max', models.PositiveSmallIntegerField(default=20)),
                ('statut', models.CharField(choices=[('programmee', 'Programmée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='programmee', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'formation',
                'verbose_name_plural': 'formations',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='CertificationPersonnel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_obtention', models.DateField()),
                ('date_expiration', models.DateField()),
                ('numero_certificat', models.CharField(blank=True, max_length=100)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detenteurs', to='rh.certification')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'certification personnel',
                'verbose_name_plural': 'certifications personnel',
                'ordering': ['-date_expiration'],
            },
        ),
        migrations.CreateModel(
            name='Garde',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_garde', models.CharField(choices=[('jour', 'Jour'), ('nuit', 'Nuit'), ('week_end', 'Week-end'), ('urgence', 'Urgence')], max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardes', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gardes', to='logistics.service')),
            ],
            options={
                'verbose_name': 'garde',
                'verbose_name_plural': 'gardes',
                'ordering': ['date_debut'],
                'indexes': [models.Index(fields=['date_debut'], name='rh_garde_date_de_b77e33_idx'), models.Index(fields=['personnel', 'date_debut'], name='rh_garde_personn_bf93fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='InscriptionFormation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('present', 'Présent'), ('valide', 'Validé'), ('absent', 'Absent')], default='inscrit', max_length=20)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='rh.formation')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_formation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inscription formation',
                'verbose_name_plural': 'inscriptions formation',
                'unique_together': {('formation', 'personnel')},
            },
        ),
    ]
