# Generated by Django 5.2.15 on 2026-07-10 17:48

from django.db import migrations, models


def normalize_empty_emails(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(email='').update(email=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountvalidation'),
    ]

    operations = [
        migrations.RunPython(normalize_empty_emails, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
