# Generated by Django 5.2.15 on 2026-07-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('medecin', 'Médecin'), ('infirmier', 'Infirmier(ère)'), ('biologiste', 'Biologiste'), ('pharmacien', 'Pharmacien'), ('comptable', 'Comptable'), ('secretaire', 'Secrétaire'), ('patient', 'Patient')], default='infirmier', max_length=20),
        ),
    ]
