# Generated by Django 5.2.10 on 2026-07-10 01:39

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('categorie', models.CharField(choices=[('consumable', 'Consommable'), ('equipment', 'Équipement'), ('medication', 'Médicament')], default='consumable', max_length=20)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('seuil_alerte', models.PositiveIntegerField(default=10)),
                ('unite', models.CharField(default='unité', max_length=20)),
                ('valeur_unitaire', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'article stock',
                'verbose_name_plural': 'articles stock',
                'ordering': ['nom'],
            },
        ),
    ]
