# Generated by Django 5.2.15 on 2026-06-03 06:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturation', '0001_initial'),
        ('laboratoire', '0001_initial'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSigne',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_document', models.CharField(choices=[('facture', 'Facture'), ('compte_rendu_labo', 'Compte-rendu laboratoire'), ('ordonnance', 'Ordonnance')], max_length=30)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/')),
                ('empreinte_sha256', models.CharField(max_length=64)),
                ('signature', models.CharField(max_length=64)),
                ('code_verification', models.CharField(max_length=12)),
                ('signe_le', models.DateTimeField()),
                ('signataire_nom', models.CharField(max_length=200)),
                ('signataire_role', models.CharField(max_length=50)),
                ('numero_reference', models.CharField(blank=True, max_length=50)),
                ('commande_analyse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_pdf', to='laboratoire.commandeanalyse')),
                ('facture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_pdf', to='facturation.facture')),
                ('prescription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_pdf', to='prescriptions.prescription')),
                ('signe_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_signes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document signé',
                'verbose_name_plural': 'documents signés',
                'ordering': ['-signe_le'],
                'indexes': [models.Index(fields=['type_document'], name='documents_d_type_do_d8aef0_idx'), models.Index(fields=['code_verification'], name='documents_d_code_ve_661e9d_idx')],
            },
        ),
    ]
