# Generated by Django 5.2.10 on 2026-07-10 01:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_patient_fix_missing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassageUrgence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_libre', models.CharField(blank=True, default='', max_length=150)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, default='', max_length=1)),
                ('motif', models.TextField()),
                ('niveau_triage', models.CharField(choices=[('red', 'Urgence majeure'), ('orange', 'Urgent'), ('green', 'Peu urgent'), ('blue', 'Non urgent')], default='orange', max_length=10)),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('triage', 'Triage en cours'), ('soins', 'En salle de soins'), ('sorti', 'Sorti'), ('admis', 'Admis en hospitalisation')], default='attente', max_length=20)),
                ('heure_arrivee', models.DateTimeField(default=django.utils.timezone.now)),
                ('heure_triage', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('medecin_triage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triages_urgence', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passages_urgence', to='patients.patient')),
            ],
            options={
                'verbose_name': 'passage urgence',
                'verbose_name_plural': 'passages urgence',
                'ordering': ['heure_arrivee'],
            },
        ),
    ]
