# Generated by Django 5.2.15 on 2026-06-03 05:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitalisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticCIM10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code CIM-10')),
                ('libelle', models.CharField(max_length=255)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'diagnostic CIM-10',
                'verbose_name_plural': 'diagnostics CIM-10',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('validee_le', models.DateTimeField(blank=True, null=True)),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='hospitalisation.hospitalisation')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_redigees', to=settings.AUTH_USER_MODEL)),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'prescription',
                'verbose_name_plural': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LignePrescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicament', models.CharField(max_length=200)),
                ('posologie', models.CharField(max_length=150)),
                ('duree_traitement', models.CharField(blank=True, max_length=100)),
                ('voie_administration', models.CharField(default='orale', max_length=50)),
                ('instructions', models.TextField(blank=True)),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'ligne de prescription',
                'verbose_name_plural': 'lignes de prescription',
                'ordering': ['ordre', 'medicament'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDiagnostic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_cim10', models.CharField(max_length=10)),
                ('libelle', models.CharField(max_length=255)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'diagnostic de prescription',
                'verbose_name_plural': 'diagnostics de prescription',
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['statut'], name='prescriptio_statut_ca9a12_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['created_at'], name='prescriptio_created_1f24b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prescriptiondiagnostic',
            unique_together={('prescription', 'code_cim10')},
        ),
    ]
