# Generated by Django 5.2.15 on 2026-06-03 04:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motif_admission', models.TextField()),
                ('date_admission', models.DateTimeField()),
                ('date_sortie_prevue', models.DateField(blank=True, null=True)),
                ('date_sortie_effective', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('sortie', 'Sortie'), ('annulee', 'Annulée')], default='active', max_length=20)),
                ('lit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalisations', to='logistics.lit')),
                ('medecin_referent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalisations_suivies', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalisations', to='patients.patient')),
            ],
            options={
                'verbose_name': 'hospitalisation',
                'verbose_name_plural': 'hospitalisations',
                'ordering': ['-date_admission'],
                'indexes': [models.Index(fields=['statut'], name='hospitalisa_statut_6a74d0_idx'), models.Index(fields=['date_admission'], name='hospitalisa_date_ad_a49128_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('statut', 'active')), fields=('patient',), name='unique_hospitalisation_active_par_patient'), models.UniqueConstraint(condition=models.Q(('statut', 'active')), fields=('lit',), name='unique_hospitalisation_active_par_lit')],
            },
        ),
    ]
