# Generated by Django 5.2.10 on 2026-07-10 01:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_patient_fix_missing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganismeAssurance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('taux_couverture', models.PositiveSmallIntegerField(default=80)),
                ('actif', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_telephone', models.CharField(blank=True, default='', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'organisme assurance',
                'verbose_name_plural': 'organismes assurance',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='AffiliationPatient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_adherent', models.CharField(blank=True, default='', max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='patients.patient')),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affiliations', to='assurance.organismeassurance')),
            ],
            options={
                'verbose_name': 'affiliation patient',
                'verbose_name_plural': 'affiliations patient',
                'ordering': ['-date_debut'],
            },
        ),
    ]
