# Generated by Django 5.2.15 on 2026-06-03 05:59

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitalisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifActe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('categorie', models.CharField(choices=[('sejour', 'Séjour'), ('laboratoire', 'Laboratoire'), ('pharmacie', 'Pharmacie'), ('soins', 'Soins'), ('divers', 'Divers')], max_length=20)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tarif acte',
                'verbose_name_plural': 'tarifs actes',
                'ordering': ['categorie', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_facture', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('validee_le', models.DateTimeField(blank=True, null=True)),
                ('payee_le', models.DateTimeField(blank=True, null=True)),
                ('mode_paiement', models.CharField(blank=True, max_length=50)),
                ('reference_paiement', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('enregistree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_payees', to=settings.AUTH_USER_MODEL)),
                ('hospitalisation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='facture', to='hospitalisation.hospitalisation')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'facture',
                'verbose_name_plural': 'factures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_acte', models.CharField(max_length=30)),
                ('libelle', models.CharField(max_length=255)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_ligne', models.DecimalField(decimal_places=2, max_digits=14)),
                ('source', models.CharField(choices=[('auto_sejour', 'Séjour (auto)'), ('auto_labo', 'Laboratoire (auto)'), ('auto_pharma', 'Pharmacie (auto)'), ('manuelle', 'Manuelle')], max_length=20)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.facture')),
            ],
            options={
                'verbose_name': 'ligne de facture',
                'verbose_name_plural': 'lignes de facture',
                'ordering': ['code_acte', 'libelle'],
            },
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['statut'], name='facturation_statut_b61650_idx'),
        ),
    ]
