# Generated by Django 5.2.15 on 2026-06-03 22:34

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant payé par le patient'),
        ),
        migrations.AddField(
            model_name='facture',
            name='tiers_payant_montant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='facture',
            name='tiers_payant_organisme',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('partiellement_payee', 'Partiellement payée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=20),
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_ecriture', models.CharField(choices=[('validation', 'Validation facture'), ('paiement_patient', 'Paiement patient'), ('paiement_tiers', 'Tiers payant')], max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('libelle', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comptable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures_comptables', to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures_comptables', to='facturation.facture')),
            ],
            options={
                'verbose_name': 'écriture comptable',
                'verbose_name_plural': 'écritures comptables',
                'ordering': ['created_at'],
            },
        ),
    ]
