# Generated by Django 5.2.15 on 2026-06-03 04:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_dossier', models.CharField(max_length=20, unique=True, verbose_name='N° dossier')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('consentement_donnees', models.BooleanField(default=False, verbose_name='Consentement traitement des données')),
                ('compte_utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
                'indexes': [models.Index(fields=['numero_dossier'], name='patients_pa_numero__169aca_idx'), models.Index(fields=['nom', 'prenom'], name='patients_pa_nom_d8dfda_idx')],
            },
        ),
    ]
