# Generated by Django 5.2.15 on 2026-06-11 04:11

from django.db import migrations, models


def add_patient_fields(apps, schema_editor):
    Patient = apps.get_model('patients', 'Patient')
    table_name = Patient._meta.db_table
    cursor = schema_editor.connection.cursor()

    if schema_editor.connection.vendor == 'sqlite':
        cursor.execute(f"PRAGMA table_info('{table_name}')")
        existing_columns = {row[1] for row in cursor.fetchall()}
    else:
        existing_columns = {
            column.name for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }

    def add_field_if_missing(name, field):
        if name not in existing_columns:
            field.set_attributes_from_name(name)
            schema_editor.add_field(Patient, field)

    add_field_if_missing('allergies', models.TextField(blank=True, default=''))
    add_field_if_missing('antecedents_medicaux', models.TextField(blank=True, default=''))
    add_field_if_missing('groupe_sanguin', models.CharField(blank=True, default='', max_length=5))
    add_field_if_missing('photo', models.CharField(blank=True, default='', max_length=100))
    add_field_if_missing('traitements_en_cours', models.TextField(blank=True, default=''))


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_patient_fields, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='patient',
                    name='allergies',
                    field=models.TextField(blank=True, default=''),
                ),
                migrations.AddField(
                    model_name='patient',
                    name='antecedents_medicaux',
                    field=models.TextField(blank=True, default=''),
                ),
                migrations.AddField(
                    model_name='patient',
                    name='groupe_sanguin',
                    field=models.CharField(blank=True, default='', max_length=5),
                ),
                migrations.AddField(
                    model_name='patient',
                    name='photo',
                    field=models.CharField(blank=True, default='', max_length=100),
                ),
                migrations.AddField(
                    model_name='patient',
                    name='traitements_en_cours',
                    field=models.TextField(blank=True, default=''),
                ),
                migrations.AlterField(
                    model_name='patient',
                    name='adresse',
                    field=models.TextField(blank=True, default=''),
                ),
                migrations.AlterField(
                    model_name='patient',
                    name='email',
                    field=models.EmailField(blank=True, default='', max_length=254),
                ),
                migrations.AlterField(
                    model_name='patient',
                    name='telephone',
                    field=models.CharField(blank=True, default='', max_length=20),
                ),
            ],
        ),
    ]
