# Generated by Django 5.2.15 on 2026-06-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationinbox',
            new_name='notificatio_utilisa_9d8291_idx',
            old_name='notificatio_utilisa_8f0b0d_idx',
        ),
    ]
